services:
  notebook:
    image: zheqijin/dsci-310-group-18:latest
    build:
      context: .
      platforms:
        - linux/arm64
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work